server:
  ip: 0.0.0.0
  port: 8000
  http_port: 8003

selected_module:
  ASR: OpenaiASR
  LLM: OpenAILLM
  TTS: FishAudio

ASR:
  OpenaiASR:
    type: openai
    api_key: ""
    base_url: https://api.openai.com/v1/audio/transcriptions
    model_name: gpt-4o-mini-transcribe
    language: en
    output_dir: tmp/

LLM:
  OpenAILLM:
    type: openai
    base_url: https://api.openai.com/v1
    model_name: gpt-4o
    api_key: ""
    max_tokens: 160
    temperature: 0.6
    top_p: 1

TTS:
  FishAudio:
    type: fish_audio
    api_url: https://api.fish.audio/v1/tts
    api_key: ""
    reference_id: ""
    latency: normal
    normalize: true
    chunk_length: 100
    top_p: 0.7
    temperature: 0.7
    repetition_penalty: 1.2

