#!/bin/bash
# Commands to diagnose Docker build failure with sherpa-onnx==1.12.11

echo "=== Docker Build Diagnostic Commands ==="
echo ""
echo "Run these commands to diagnose the exact failure:"
echo ""
echo "1. Build Docker image with verbose output to see exact error:"
echo "   docker build -f Dockerfile-server --progress=plain --no-cache -t test-sherpa-build . 2>&1 | tee docker-build.log"
echo ""
echo "2. Test pip install directly in a Python 3.10 container:"
echo "   docker run --rm -it python:3.10-slim bash -c '"
echo "     pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \\"
echo "     pip config set global.trusted-host mirrors.aliyun.com && \\"
echo "     pip install --upgrade pip setuptools wheel && \\"
echo "     pip index versions sherpa-onnx && \\"
echo "     pip install --verbose sherpa-onnx==1.12.11'"
echo ""
echo "3. Test with 1.12.15 (known working version) for comparison:"
echo "   docker run --rm -it python:3.10-slim bash -c '"
echo "     pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \\"
echo "     pip config set global.trusted-host mirrors.aliyun.com && \\"
echo "     pip install --upgrade pip setuptools wheel && \\"
echo "     pip install --verbose sherpa-onnx==1.12.15'"
echo ""
echo "4. Check what versions are actually available in Aliyun mirror:"
echo "   docker run --rm -it python:3.10-slim bash -c '"
echo "     pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \\"
echo "     pip config set global.trusted-host mirrors.aliyun.com && \\"
echo "     pip index versions sherpa-onnx'"
echo ""
echo "=== Expected Result ==="
echo "1.12.11 does NOT exist on PyPI (confirmed by tests)"
echo "Available versions in 1.12.x series: 1.12.15, 1.12.17-1.12.23"
echo ""
echo "The Docker build fails because pip cannot find sherpa-onnx==1.12.11"
echo "You MUST upgrade to at least 1.12.15 (or any newer 1.12.x version)"
